In [226]:
import os

import numpy as np

import matplotlib
import matplotlib.pyplot as plt

import scipy.io
from scipy.io import loadmat

import mne

In [227]:
mat_data = loadmat('ADHD_part2/v177.mat')

eeg_data = mat_data['v177']


The loadmat automatically turns our data within the key `177` into a NumPy array which we refernece to as `v177`.

In [228]:
ch_names = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19']
sfreq = 128

info = mne.create_info(ch_names = ch_names, sfreq=sfreq, ch_types = 'eeg')

eeg_data = eeg_data.T

We assign channel names and sampling frequencies to the corresponding variables.

Then using the `mne.create_info()` function, we create an info object that holds metadata on our EEG dataset.

In [229]:
raw = mne.io.RawArray(eeg_data, info)

Creating RawArray with float64 data, n_channels=19, n_times=16697
    Range : 0 ... 16696 =      0.000 ...   130.438 secs
Ready.


In [230]:
%matplotlib inline
raw.plot(n_channels=19, duration=10, start=0)

Using pyopengl with version 3.1.6


The `mne.io.RawArray()` function, gets our raw EEG data and other metadata to create a `raw` object in MNE from our EEG data stored in our NumPy array of `v177`.

`v177.T` transposes our NumPy array turning it into a format designated for use in MNE (channels in rows, time points in columns).

Our metadata stored in the `info` object is called by the `RawArray()` function. 

The transposed `v177.T` and `info` is stored in the `raw` object.

In [231]:
#raw.filter(l_freq=1, h_freq=40)

The `raw.filter()` function applies a bandpass frequency with the lowpass at 1 Hz and highpass at 40 Hz.

In [232]:
##%matplotlib inline
##raw.plot(n_channels=19, duration=10, start=10)

In [233]:
print(v177.min(axis=0))
print(v177.max(axis=0))

[-3082. -3715.  -609. -1603.  -462. -1860.  -572. -1603.  -940. -1603.
 -3921. -3921.  -903. -1713. -2080. -1603. -3751. -1639.  -442.]
[2514. 2303.  825. 1317.  825. 1193.  862. 1524. 1009. 1488. 2555. 5020.
 1267. 1304.  752. 1377. 2761. 1282.  684.]


In [234]:
print(info.ch_names)

['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19']


In [235]:
print(eeg_data.shape)


(19, 16697)


In [236]:
print(info['sfreq'])

128.0


In [237]:
print(eeg_data[:10, :])  # Print the first 10 rows (adjust as needed)

[[   85.   121.   191. ... -1075.  -970. -1075.]
 [  -19.   -55.    85. ...  -407.  -407.  -407.]
 [  163.   273.   347. ...    16.    16.   -20.]
 ...
 [  310.   420.   568. ...   310.   273.   347.]
 [  568.   678.   715. ...   457.   163.   -57.]
 [  310.   494.   568. ...   273.   310.   347.]]
Channels marked as bad:
none
