In [10]:
import os
import glob

import numpy as np

import matplotlib
import matplotlib.pyplot as plt

import scipy.io
from scipy.io import loadmat

import mne

In [11]:
matfiles = glob.glob('MNE-EEG-PROCESSING/ADHD_part2/*.mat') 

data = {}
matfiles

['MNE-EEG-PROCESSING/ADHD_part2/v177.mat',
 'MNE-EEG-PROCESSING/ADHD_part2/v215.mat',
 'MNE-EEG-PROCESSING/ADHD_part2/v200.mat',
 'MNE-EEG-PROCESSING/ADHD_part2/v213.mat',
 'MNE-EEG-PROCESSING/ADHD_part2/v206.mat',
 'MNE-EEG-PROCESSING/ADHD_part2/v204.mat',
 'MNE-EEG-PROCESSING/ADHD_part2/v238.mat',
 'MNE-EEG-PROCESSING/ADHD_part2/v198.mat',
 'MNE-EEG-PROCESSING/ADHD_part2/v263.mat',
 'MNE-EEG-PROCESSING/ADHD_part2/v288.mat',
 'MNE-EEG-PROCESSING/ADHD_part2/v274.mat',
 'MNE-EEG-PROCESSING/ADHD_part2/v270.mat',
 'MNE-EEG-PROCESSING/ADHD_part2/v265.mat',
 'MNE-EEG-PROCESSING/ADHD_part2/v254.mat',
 'MNE-EEG-PROCESSING/ADHD_part2/v286.mat',
 'MNE-EEG-PROCESSING/ADHD_part2/v279.mat',
 'MNE-EEG-PROCESSING/ADHD_part2/v250.mat',
 'MNE-EEG-PROCESSING/ADHD_part2/v244.mat',
 'MNE-EEG-PROCESSING/ADHD_part2/v246.mat',
 'MNE-EEG-PROCESSING/ADHD_part2/v284.mat',
 'MNE-EEG-PROCESSING/ADHD_part2/v181.mat',
 'MNE-EEG-PROCESSING/ADHD_part2/v234.mat',
 'MNE-EEG-PROCESSING/ADHD_part2/v209.mat',
 'MNE-EEG-P

In [12]:
mat_data = loadmat(matfiles[0])

eeg_data = mat_data['v177']

The loadmat automatically turns the EEG data represented by the name `v177` into a NumPy array which we refernece to as `eeg_data`.

In [13]:
ch_names = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19']
sfreq = 128

info = mne.create_info(ch_names = ch_names, sfreq=sfreq, ch_types = 'eeg')

eeg_data = eeg_data.T

We assign channel names and sampling frequencies to the corresponding variables.

Then using the `mne.create_info()` function, we create an info object that holds metadata on our EEG dataset.

Using `eeg_data.T` we transpose our NumPy array and re-assign it to the object `eeg_data`

In [14]:
raw = mne.io.RawArray(eeg_data, info)

Creating RawArray with float64 data, n_channels=19, n_times=16697
    Range : 0 ... 16696 =      0.000 ...   130.438 secs
Ready.


In [15]:
%matplotlib inline
raw.plot(n_channels=19, duration=1000, start=0)

Using pyopengl with version 3.1.6


The `mne.io.RawArray()` function, gets our raw EEG data and other metadata to create a `raw` object in MNE from our EEG data stored in our NumPy array of `v177`.

`v177.T` transposes our NumPy array turning it into a format designated for use in MNE (channels in rows, time points in columns).

Our metadata stored in the `info` object is called by the `RawArray()` function. 

The transposed `v177.T` and `info` is stored in the `raw` object.

In [16]:
#raw.filter(l_freq=1, h_freq=40)

The `raw.filter()` function applies a bandpass frequency with the lowpass at 1 Hz and highpass at 40 Hz.

In [17]:
##%matplotlib inline
##raw.plot(n_channels=19, duration=10, start=10)

In [19]:
print(eeg_data.min(axis=0))
print(eeg_data.max(axis=0))

[  -19.   -55.    85. ... -1075.  -970. -1075.]
[568. 678. 715. ... 457. 310. 347.]


In [20]:
print(info.ch_names)

['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19']


In [21]:
print(eeg_data.shape)


(19, 16697)


In [22]:
print(info['sfreq'])

128.0


In [23]:
print(eeg_data[:10, :])  # Print the first 10 rows (adjust as needed)

[[   85.   121.   191. ... -1075.  -970. -1075.]
 [  -19.   -55.    85. ...  -407.  -407.  -407.]
 [  163.   273.   347. ...    16.    16.   -20.]
 ...
 [  310.   420.   568. ...   310.   273.   347.]
 [  568.   678.   715. ...   457.   163.   -57.]
 [  310.   494.   568. ...   273.   310.   347.]]
